### ISSUE TITLE
Format the command options in a tabular format

### ISSUE THREAD

**Issue by hemchander23** [hemchander23/commandline_meme_generator#1]
I would need some help to format the options that are mentioned below the command into a **tabular format**

https://github.com/hemchander23/commandline_meme_generator#example-

![image](https://user-images.githubusercontent.com/19341550/66318001-29309180-e938-11e9-8fc1-f1e9c3742fe7.png)

This has to be put in a markdown table 

Kindly follow the contribution guidelines :) !

https://github.com/hemchander23/commandline_meme_generator#to-contribute

**Comment by deschantkn** [comment]
I would like to work on this task

**Comment by hemchander23** [comment]
Feel free to work on this one ! @deschantkn 🎉

**Comment by hemchander23** [comment]
Quick note: `|` pipe symbol is used as a seperator in text and position parameter

**Comment by deschantkn** [comment]
What would you like to have as column names for the table?

**Comment by hemchander23** [comment]
Short Flag, Long name, Description would be great 🙂

Reference : https://github.com/tj/commander.js#options

**Comment by deschantkn** [comment]
Here you go! https://github.com/hemchander23/commandline_meme_generator/pull/3
Let me know if you've got any comments!

**Comment by hemchander23** [comment]
Thanks for the contribution @deschantkn ! The PR is merged. ⭐️ Star the repo if you found it useful. Happy Hacktoberfest !! 🎃
