### ISSUE TITLE
Set default value for commander option

### ISSUE THREAD

**Issue by hemchander23** [hemchander23/commandline_meme_generator#2]
We need to set default values for the meme generator. In this case, let's just look at the `scale` option. Scale should be `1.0` by default

Commander reference : https://github.com/tj/commander.js/#default-option-value

Kindly follow the contribution guidelines :) - https://github.com/hemchander23/commandline_meme_generator#to-contribute

**Comment by PoojaKhandhadia** [comment]
I will work on it :)

**Comment by hemchander23** [comment]
Thanks @PoojaKhandhadia !

**Comment by hemchander23** [comment]
Thanks for the contribution @PoojaKhandhadia ! The PR is merged. ⭐️ Star the repo if you found it useful. Happy Hacktoberfest !! 🎃
