### ISSUE TITLE
Clean up the downloaded file after converting to meme

### ISSUE THREAD

**Issue by hemchander23** [hemchander23/commandline_meme_generator#5]
When you create a meme from URL, it leaves a residual file after download due to the current implementation

`mkmeme create-meme "All memes are dying|This meme:" -i "https://i.imgflip.com/2gnnjh.jpg" -p "10|150"`

_File indicated by green arrow is the residual file in this case_

<img width="368" alt="Screenshot 2019-10-07 at 9 50 15 PM" src="https://user-images.githubusercontent.com/19341550/66329655-7e769e00-e94c-11e9-8a1b-e591ea9cf455.png">

Suggest and implement a solution that either avoids or cleans up this file automatically. Feel free to work on the issue and raise PRs 

Note : Kindly follow the contribution guidelines :) !

https://github.com/hemchander23/commandline_meme_generator#to-contribute

**Comment by suganya-sangith** [comment]
@hemchander23 Will work on it

**Comment by suganya-sangith** [comment]
@hemchander23 Will work on it

**Comment by hemchander23** [comment]
Amazing :) @suganya-sangith 🎉

**Comment by suganya-sangith** [comment]
@hemchander23 
We can clear the downloaded input image, but we should not clear the output image as it is required.

Output.jpg can be added in .gitignore file.
Also will remove deleted files mentioned in .gitignore

Please let me know whether this is fine

**Comment by hemchander23** [comment]
Hi @suganya-sangith as you mentioned rightly, the downloaded input image has to be automatically deleted after a successful conversion. It should be treated like a temp file

Output image is required and hence cannot be deleted. 

It also makes sense to add it in the .gitignore.
